### ISSUE TITLE
Consolidate examples (e.g https://troubleshoot.replicated.com)

### ISSUE THREAD

**Issue by markpundsack** [replicatedhq/troubleshoot.sh#156]
https://github.com/replicatedhq/troubleshoot refers to https://preflight.replicated.com and https://troubleshoot.replicated.com as examples to run. We're currently proposing different examples for the Troubleshoot.sh examples. Maybe we should just update those examples on replicated.com and point to those? I think I prefer `replicated.com` over `troubleshoot.sh` as the hostname for the examples.

**Comment by GraysonNull** [comment]
@markpundsack just so I'm clear, should we update the examples shown on troubleshoot.sh with the ones shown on `preflight.` and `troubleshoot.` (`troubleshoot.` 404's btw) or should the README for the troubleshoot repo point to the new examples we're using on troubleshoot.sh?

And then once those are normalized, host them from `replicated.com` and have both docs point to that as the host.

**Comment by markpundsack** [comment]
@GraysonNull We have three places that refer to examples:
1. Troubleshoot.sh homepage video (https://troubleshoot.sh/examples/preflight.yaml)
1. Troubleshoot.sh getting started doc (inline text)
1. Troubleshoot repo README.md (https://preflight.replicated.com)

Goals:
1. I'd like all three to point to the same URLs.
1. I'd like the examples to be good, representative examples.
1. I'd like the URLs to be short and logical.

So far, the examples you've used in the video seem the best.

Proposal:
1. Move the content of `https://troubleshoot.sh/examples/preflight.yaml` to `https://raw.githubusercontent.com/replicatedhq/kots-default-yaml/master/preflight.yaml`. Same for support-bundle.yaml.
1. Change video to use https://preflight.replicated.com
1. Change getting started to use https://preflight.replicated.com and drop inline text (it would be too big).

I'm open to using different a different URL. But https://preflight.replicated.com is compact, and reminds people that Replicated is behind the tool. There's a good argument for basing it off of troubleshoot.sh instead, but the current URL is too long. Maybe something with `troubleshoot.run`? And then we could put the example into the documented examples too...

**Comment by AmberAlston** [comment]
I'm going to close this due to age. It looks like it may have been done already, but if not and you think it's still worth doing, please reopen or resubmit
