### ISSUE TITLE
Redact data from log files via "support-bundle" plugin 

### ISSUE THREAD

**Issue by atulsingh0** [replicatedhq/troubleshoot.sh#518]
Hi Folks,
I am trying to use "support-bundle" plugin to redact few log line from k8s pod logs, but it seems like it does not support this feature. 

Example- 

```shell
-- running 'appstar run -config=/etc/appstar -encrypt=VFpKTXBODRUM0MwZW1hekM='
==> Loaded configuration from /etc/appstar/appstar.cnf
==> Starting appstar...
==> appstar configuration:
``` 

I am trying to redact the encryption key mentioned in the log file, Can we achieve the same in support-bundle plugin?

**Comment by xavpaice** [comment]
Hi @atulsingh0, sorry it's take so long to respond - this repo isn't monitored as closely as we'd like.

You should be able to use the file and regex params to select the right file, and use a regex to perform the redaction.

If this isn't working, please feel free to submit a support request via Vendor Portal, or the [community](https://community.replicated.com/) pages.  We'd want to see the spec you're using, and if there's a way to reproduce.
